name: 'SSH Agent Action'
description: 'Starts and SSH agent and adds a private key'
author: 'TrueMark'
branding:
  icon: 'check-circle'
  color: 'red'
inputs:
  private-key-path:
    required: false
    description: 'Path to the private key'
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
  ssh-auth-sock:
    description: 'Path to the socket of the SSH agent'
